# General config
status: "Ain't got time to rock the ruckus. Time to roll! ðŸ¤˜"
prefix: "="
leave_seconds: 5 # unused, fuck python's async 

# Token generator config
# Don't change these settings unless you know what you're doing
node_script: "utilities/generator/examples/one-shot.js"
time_limit: 3
max_retries: 5
retry_delay: 2

# Commands and their aliases. Only add or remove the list contents,
# not the commands themselves
commands:
  play: 
    - p
    - pl
  pause:
    - ps
  resume:
    - res
    - rs
  repeat:
    - r
  stop:
    - st
  clear:
    - cl
  leave:
    - lv
  skip:
    - s
  remove:
    - rm
    - delete
    - del
    - d
  now_playing:
    - np
  queue:
    - q
  lyrics:
    - l

